import{useEffect,useMemo,useRef,useState}from"react";
import type{PointerEvent}from"react";
import{Peer}from"peerjs";
import{applyCapture,territoryCount}from"./game/board";
import{BOARD_SIZES,TEAM_COLORS,type BoardSize,type CellState,type Exercise,type TeamColor}from"./game/types";
import{PoseCamera}from"./features/pose/PoseCamera";
import{initTelegram,openTelegramLink,telegramUserName}from"./telegram";
type Screen="home"|"setup"|"waiting"|"join"|"battle"|"training";
type Packet={type:"hello"|"config"|"ready"|"rep"|"start";name?:string;exercise?:Exercise;size?:BoardSize;color?:TeamColor;index?:number;cells?:[number,CellState][]};
const uid=()=>Math.random().toString(36).slice(2,8).toUpperCase();
const labels={pushup:["Отжимания","Push-ups"],squat:["Приседания","Squats"]};
export default function App(){
 const[screen,setScreen]=useState<Screen>("home"),[exercise,setExercise]=useState<Exercise>("pushup"),[size,setSize]=useState<BoardSize>(100),[myColor,setMyColor]=useState<TeamColor>("red"),[oppColor,setOppColor]=useState<TeamColor>("blue"),[room,setRoom]=useState(""),[connected,setConnected]=useState(false),[status,setStatus]=useState(""),[cells,setCells]=useState(new Map<number,CellState>()),[target,setTarget]=useState(0),[myReps,setMyReps]=useState(0),[oppReps,setOppReps]=useState(0),[showHelp,setShowHelp]=useState(false),[lang,setLang]=useState<"ru"|"en">("ru");
 const peerRef=useRef<Peer|null>(null),connRef=useRef<any>(null),canvas=useRef<HTMLCanvasElement>(null);
 const t=(ru:string,en:string)=>lang==="ru"?ru:en;
 useEffect(()=>{initTelegram();const q=new URLSearchParams(location.search).get("room");if(q){setRoom(q.toLowerCase());setScreen("join")}},[]);
 const destroyPeer=()=>{connRef.current?.close();peerRef.current?.destroy();connRef.current=null;peerRef.current=null;setConnected(false)};
 useEffect(()=>()=>destroyPeer(),[]);
 const attach=(conn:any,host:boolean)=>{connRef.current=conn;conn.on("open",()=>{setConnected(true);setStatus(t("Соперник подключён","Opponent connected"));if(host)conn.send({type:"hello",name:telegramUserName(),exercise,size,color:myColor})});
  conn.on("data",(m:Packet)=>{if(m.type==="hello"){setConnected(true);setScreen("battle");setExercise(m.exercise||"pushup");setSize(m.size||100);setOppColor(m.color||"blue");conn.send({type:"config",exercise:m.exercise||exercise,size:m.size||size,color:myColor,cells:[...cells]})}else if(m.type==="config"){setExercise(m.exercise||"pushup");setSize(m.size||100);setOppColor(m.color||"blue");if(m.cells)setCells(new Map(m.cells));setScreen("battle")}else if(m.type==="rep"&&typeof m.index==="number"){setCells(v=>applyCapture(v,m.index!,m.color||oppColor));setOppReps(v=>v+1)}else if(m.type==="start")setScreen("battle")});
  conn.on("close",()=>{setConnected(false);setStatus(t("Соперник вышел","Opponent left"))});conn.on("error",()=>setStatus(t("Не удалось соединиться","Connection failed")))};
 const createRoom=()=>{destroyPeer();const code="rc-"+uid().toLowerCase();setRoom(code);const p=new Peer(code);peerRef.current=p;p.on("connection",c=>attach(c,true));p.on("error",()=>setStatus(t("Комната занята — создай ещё раз","Room unavailable — create again")));setScreen("waiting");setStatus(t("Ждём соперника…","Waiting for opponent…"))};
 const joinRoom=()=>{if(!room)return;destroyPeer();const p=new Peer();peerRef.current=p;p.on("open",()=>{const c=p.connect(room,{reliable:true});attach(c,false)});p.on("error",()=>setStatus(t("Комната не найдена или закрыта","Room not found or closed")))};
 const invite=()=>{const url=location.origin+location.pathname+"?room="+encodeURIComponent(room),share="https://t.me/share/url?url="+encodeURIComponent(url)+"&text="+encodeURIComponent(t("🏋️ Присоединяйся к моей REPCLASH битве!","🏋️ Join my REPCLASH battle!"));openTelegramLink(share)};
 const sendRep=()=>{if(!connected)return;setCells(v=>applyCapture(v,target,myColor));setMyReps(v=>v+1);connRef.current?.send({type:"rep",index:target,color:myColor})};
 const beginTraining=()=>{setScreen("training");setCells(new Map());setMyReps(0)};
 const visibleGrid=useMemo(()=>size<=100?size:40,[size]);
 useEffect(()=>{if(screen!=="battle"&&screen!=="training")return;const c=canvas.current;if(!c)return;const w=Math.min(c.clientWidth,760),d=Math.min(devicePixelRatio||1,2);c.width=w*d;c.height=w*d;const g=c.getContext("2d")!;g.setTransform(d,0,0,d,0,0);g.fillStyle="#080a0e";g.fillRect(0,0,w,w);const q=w/visibleGrid;
  for(let y=0;y<visibleGrid;y++)for(let x=0;x<visibleGrid;x++){const i=y*visibleGrid+x,v=cells.get(i),owner=v?.owner;g.fillStyle=owner?TEAM_COLORS[owner]:"#151922";g.globalAlpha=owner?(.18+(v?.strength||1)*.16):1;g.fillRect(x*q+1,y*q+1,q-2,q-2)}
  g.globalAlpha=1;g.strokeStyle="#252a35";g.lineWidth=1;for(let i=0;i<=visibleGrid;i++){g.beginPath();g.moveTo(i*q,0);g.lineTo(i*q,w);g.stroke();g.beginPath();g.moveTo(0,i*q);g.lineTo(w,i*q);g.stroke()}
 },[cells,visibleGrid,screen]);
 const pick=(e:PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect(),q=r.width/visibleGrid,x=Math.max(0,Math.min(visibleGrid-1,Math.floor((e.clientX-r.left)/q))),y=Math.max(0,Math.min(visibleGrid-1,Math.floor((e.clientY-r.top)/q)));setTarget(y*visibleGrid+x)};
 const reset=()=>{destroyPeer();setScreen("home");setRoom("");setConnected(false)};
 return <main className="app"><header className="topbar"><button className="icon-btn" onClick={reset}>R</button><div className="brand"><span>REP</span><b>CLASH</b></div><div className="top-actions"><button className="round-btn" onClick={()=>setLang(v=>v==="ru"?"en":"ru")}>{lang.toUpperCase()}</button><button className="round-btn" onClick={()=>setShowHelp(true)}>?</button></div></header>
 {screen==="home"&&<section className="home"><div className="hero-card"><div className="hero-kicker">REPCLASH / REAL-TIME FITNESS BATTLE</div><h1>{t("Сделай REP. Забери территорию.","Make a REP. Take the territory.")}</h1><p>{t("Камера считает технику. Каждый чистый повтор усиливает твою территорию.","AI checks your form. Every clean rep strengthens your territory.")}</p><div className="hero-actions"><button className="cta" onClick={()=>setScreen("setup")}>{t("СОЗДАТЬ БИТВУ","CREATE BATTLE")} <span>↗</span></button><button className="ghost" onClick={()=>setScreen("join")}>{t("ВОЙТИ ПО КОДУ","JOIN WITH CODE")}</button></div></div><div className="feature-row"><div><b>AI POSE</b><span>{t("Отжимания и приседания","Push-ups & squats")}</span></div><div><b>P2P</b><span>{t("Два игрока","Two players")}</span></div><div><b>100 → 100K</b><span>{t("Размер арены","Arena scale")}</span></div></div><button className="training-link" onClick={beginTraining}>▹ {t("Попробовать AI без соперника","Try AI without an opponent")}</button></section>}
 {screen==="setup"&&<section className="panel animate"><div className="section-head"><div><span className="eyebrow">01 / BATTLE SETUP</span><h2>{t("Собери свою арену","Build your arena")}</h2></div><button className="round-btn" onClick={()=>setShowHelp(true)}>?</button></div><div className="field"><label>{t("УПРАЖНЕНИЕ","EXERCISE")}</label><div className="choice-grid two">{(["pushup","squat"]as Exercise[]).map(x=><button key={x} className={"choice "+(exercise===x?"selected":"")} onClick={()=>setExercise(x)}><span>{x==="pushup"?"↘":"◒"}</span><b>{t(labels[x][0],labels[x][1])}</b><small>{x==="pushup"?t("Грудь · руки · корпус","Chest · arms · core"):t("Ноги · колени · таз","Legs · knees · hips")}</small></button>)}</div></div><div className="field"><label>{t("РАЗМЕР ТЕРРИТОРИИ","TERRITORY SIZE")}</label><div className="size-grid">{BOARD_SIZES.map(x=><button key={x} className={"size-card "+(size===x?"selected":"")} onClick={()=>setSize(x)}><b>{x.toLocaleString()}</b><small>× {x.toLocaleString()}</small></button>)}</div></div><div className="field"><label>{t("ТВОЙ ЦВЕТ","YOUR COLOR")}</label><div className="colors">{(Object.keys(TEAM_COLORS)as TeamColor[]).map(x=><button aria-label={x} key={x} className={"color-btn "+(myColor===x?"active":"")} style={{background:TEAM_COLORS[x]}} onClick={()=>setMyColor(x)}/>)}</div></div><button className="cta full" onClick={createRoom}>{t("СОЗДАТЬ И ПРИГЛАСИТЬ","CREATE & INVITE")} <span>→</span></button></section>}
 {screen==="waiting"&&<section className="panel waiting animate"><div className="waiting-orb">⚡</div><span className="eyebrow">ROOM READY</span><h2>{t("Ждём второго игрока","Waiting for player 2")}</h2><p>{t("Сначала соперник принимает приглашение. После этого откроется общая арена.","The battle starts only after your opponent joins.")}</p><div className="room-code">{room}</div><button className="cta full" onClick={invite}>{t("ПРИГЛАСИТЬ В TELEGRAM","INVITE ON TELEGRAM")} ↗</button><div className="waiting-meta"><span>{t("Упражнение","Exercise")} <b>{t(labels[exercise][0],labels[exercise][1])}</b></span><span>{t("Арена","Arena")} <b>{size.toLocaleString()}×{size.toLocaleString()}</b></span></div><div className={"connection "+(connected?"ok":"")}>● {connected?t("СОПЕРНИК ПОДКЛЮЧЁН","OPPONENT CONNECTED"):t("ЖДЁМ ПОДКЛЮЧЕНИЯ","WAITING FOR CONNECTION")}</div></section>}
 {screen==="join"&&<section className="panel join animate"><span className="eyebrow">JOIN BATTLE</span><h2>{t("Вход в битву","Join a battle")}</h2><p>{t("Вставь код комнаты из приглашения.","Paste the room code from the invite.")}</p><input className="room-input" value={room} onChange={e=>setRoom(e.target.value.toLowerCase())} placeholder="rc-xxxxxx"/><div className="field"><label>{t("ТВОЙ ЦВЕТ","YOUR COLOR")}</label><div className="colors">{(Object.keys(TEAM_COLORS)as TeamColor[]).map(x=><button aria-label={x} key={x} className={"color-btn "+(myColor===x?"active":"")} style={{background:TEAM_COLORS[x]}} onClick={()=>setMyColor(x)}/>)}</div></div><button className="cta full" onClick={joinRoom}>{t("ПОДКЛЮЧИТЬСЯ","CONNECT")} →</button><button className="ghost full" onClick={()=>setScreen("home")}>{t("НАЗАД","BACK")}</button><div className="connection">{status||t("P2P-подключение","P2P connection")}</div></section>}
 {(screen==="battle"||screen==="training")&&<section className="battle-layout animate"><div className="battle-main"><div className="battle-head"><div><span className="eyebrow">{screen==="training"?"AI TRAINING":"LIVE BATTLE"}</span><h2>{size.toLocaleString()} × {size.toLocaleString()}</h2></div><div className="score"><span>{myReps} <small>YOU</small></span><i>:</i><span>{oppReps} <small>RIVAL</small></span></div></div><div className="arena"><canvas ref={canvas} onPointerUp={pick}/><div className="arena-grid-label">{t("МАСШТАБ АРЕНЫ","ARENA SCALE")} · {size.toLocaleString()}×{size.toLocaleString()}</div><div className="target-dot" style={{left:(((target%visibleGrid)+.5)*100/visibleGrid)+"%",top:((Math.floor(target/visibleGrid)+.5)*100/visibleGrid)+"%"}}/></div><div className="battle-actions"><button className="cta" disabled={!connected&&screen==="battle"} onClick={sendRep}>+1 REP → {t("ЗАХВАТИТЬ","CAPTURE")}</button><button className="ghost" onClick={()=>setShowHelp(true)}>?</button></div><div className="territory-row"><span>{t("Твоя территория","Your territory")} <b>{territoryCount(cells,myColor)}</b></span><span>{t("Цель","Target")} <b>#{target+1}</b></span></div></div><PoseCamera enabled exercise={exercise} onRep={e=>{if(e.ok){if(screen==="training")setMyReps(v=>v+1);else sendRep()}}}/></section>}
 {showHelp&&<div className="modal-backdrop" onPointerDown={()=>setShowHelp(false)}><div className="modal" onPointerDown={e=>e.stopPropagation()}><button className="modal-x" onClick={()=>setShowHelp(false)}>×</button><span className="eyebrow">HOW REPCLASH WORKS</span><h2>{t("Как это работает","How it works")}</h2><p>1. {t("Создай битву и выбери упражнение.","Create a battle and choose an exercise.")}</p><p>2. {t("Пригласи соперника. Пока он не подключился — битва не начинается.","Invite your opponent. The battle does not start until they join.")}</p><p>3. {t("Камера считает чистые повторения.","The camera counts clean reps.")}</p><p>4. {t("Выбирай клетку и захватывай территорию.","Pick a cell and capture territory.")}</p><button className="cta full" onClick={()=>setShowHelp(false)}>{t("ПОНЯТНО","GOT IT")}</button></div></div>}</main>
}
